\input texinfo @c -*-mode:texinfo; compile-command: "makeinfo gtypist.texi"-*-
@setfilename gtypist.info
@settitle Pøíruèka pro GTypist
@documentlanguage cs
@documentencoding ISO-8859-2
@include version.texi

@copying
Toto je manuál pro GNU Typist (verze @value{VERSION}, @value{UPDATED}),
program urèený k výuce psaní na klávesnici pro nìkolik
jazykù a rùzné klávesové rozlo¾ení.

Copyright @copyright{} 1998, 1999, 2000, 2001, 2002
Free Software Foundation, Inc.

@quotation
Dáváme povolení ke kopírování, distribuci a/nebo provádìní
zmìn v tomto dokumentu pod podmínkami GNU Free Documentation
License verze 1.1 nebo jakékoliv pozdìj¹í verze publikované
Nadací pro svobodný software (Free Software Foundation); text
neobsahuje ¾ádnou Invariant Section, Front Cover text je
,,GNU Manuál'' a Back-Cover Text je uveden v (a) ní¾e.
Kopie licence je pøilo¾ena v sekci nazvané ,,GNU Free
Docuemntation License''.

(a) Back Cover Text FSF je: ,,Máte svobodu kopírovat
a modifikovat tento GNU manuál stejnì jako GNU software.
Výtì¾ek z kopií publikovaných Nadací pro svobodný software
jsou pou¾ity na vývoj GNU.''
@end quotation
@end copying

@dircategory Education
@direntry Education
* GTypist: (gtypist). Dokumentace k výukovému programu psaní
na klávesnici gtypist.
@end direntry

@titlepage
@title Pøíruèka pro GNU Typist
@subtitle Verze @value{VERSION}
@author Poslední update: @value{UPDATED}
@page
@vskip 0pt plus 1filll
@insertcopying
Publikováno Nadací pro svobodný software @*
59 Temple Place Suite 330 @*
Boston, MA 02111-1307 @*
USA @*
@end titlepage

@contents

@page

@ifnottex
@node Top, Distribuce, (dir), (dir)
@top GNU Typist - psaní v¹emi deseti
@insertcopying

GNU Typist je interaktivní výukový program, který vám pomù¾e
osvojit si principy správného psaní na klávesnici v¹emi deseti prsty.
Obsahuje nìkolik lekcí pro rùzné typy klávesnic a rùzné jazyky. (Mezi
nimi nechybí ani èe¹tina.) Lekce pro gtypist jsou napsány ve snadno
pochopitelném skriptovacím jazyku, tak¾e je mohou u¾ivatelé
modifkovat èi vytváøet nové. Pokud zadáte parametr cs.typ,
spustíte lekce v èe¹tinì zamìøené na èeskou klávesnici.

@end ifnottex

@menu
@c TODO:
* Distribuce::              Kde najít gtypist: zdrojové kódy, balíèky apod.
* Kopírování::              Kopírování a svobodné sdílení gtypist pod GPL
* Úvod::         	    Co byste mìli jako u¾ivatelé vìdìt
* Spou¹tìní::               Jak spustit gtypist
* Dostupné lekce::          Pøehled lekcí v distribuci gtypistu
* Pou¾ívání typefortune::   Procvièování na textu z `fortune' (perl)
* Pøíkazy skriptovacího jazyka::    Informace o syntaxi lekcí pro gtypist
* Vytvoøte nové lekce::     Jak pøispìt novými lekcemi
* Mód Emacsu::              Mód Emacsu pro editaci skriptù do gtypistu
* Promìnné prostøedí::      Promìnné prostøedí, které ovlivòují gtypist
* Chyby a opominutí::       Známé problémy
* Historie::                Historie GNU Typistu
* Kopírování tohoto manuálu::	Licence svobodné dokumentace GNU.
@end menu

@node Distribuce, Kopírování, Top, Top
@unnumbered Distribuce

GNU Typist (èi gtypist) je @dfn{svobodný software}; to znamená, ¾e
jej mù¾e za urèitých podmínek ka¾dý svobodnì pou¾ívat a 
dále redistribuovat. Pøesné podmínky mù¾ete nalézt v GNU
General Public Lincense, kterou jste obdr¾eli s tímto programem
a která následuje tuto sekci.

@noindent
GNU Typist mù¾ete získat od pøítele nebo z Internetu:

@table @asis

@item Hlavní distribuèní web:
@url{ftp://ftp.gnu.org/gnu/gtypist/}

@item Domovská stránka
@url{http://www.gnu.org/software/gtypist/gtypist.cs.html}

@item On-line manuál (aktualizace mezi vydáním jednotlivých verzí)
@url{http://www.gnu.org/software/gtypist/doc/}

@item Stránka vývojáøù (CVS repozitáø, úlohy, podpora...)
@url{http://savannah.gnu.org/projects/gtypist/}

@item Sta¾ení GNU Typist (zdrojové kódy, binární verze, tutoriály)
@url{http://gtypist.free.fr/}

@item Obrázky
@url{http://gtypist.free.fr/screenshots/}
@end table

@node Kopírování, Úvod, Distribuce, Top
@include gpl.texi

@node Úvod, Spou¹tìní, Kopírování, Top
@chapter Úvod

GNU Typist je interaktivní program pro výuku psaní na klávesnici
v¹emi deseti prsty. Obsahuje výukové lekce, cvièení i rychlostní
testy. Program je urèen pro pou¾ívání na terminálech bez grafiky.
Byl zkompilován na GNU/Linuxu, Unixech (Aix, OpenBSD) a také
na DOS/Windows (DOS 6.22, Windows 98, Windows NT).

Program naèítá lekce vytvoøené ve snadno pochopitelném 
skritpovacím jazyku. Je distribuován spolu s nìkolika
dobrými a kompletními lekcemi, které mù¾ete pou¾ívat,
modifikovat, nebo psát nové. (@pxref{Vytvoøte nové lekce}
@pxref{Pøíkazy skriptovacího jazyka}).

Pokud nespecifikujete pøíslu¹ný soubor lekcí na pøíkazové øádce, bude pou¾it
@file{gtypist.typ}. (Podrobnosti o cestì k souborùm naleznete v sekci
@pxref{Promìnné prostøedí}).

Na horní øádce obrazovky naleznete banner programu. Na nejspodnìj¹í
øádce se potom nalézají rùzné zprávy, dotazy a dal¹í informace
o stavu. Øádky mezi tím jsou pou¾ívány pro tutoriály, cvièení
a rychlostní testy.

V programu jsou dva typy cvièení: drilové a rychlostní testy.

V drilových vám gtypist zobrazí text v ka¾dé druhé øádce obrazovky
a poèká, a¾ u¾ivatel správnì opí¹e text do zbývajících prázdných
øádek. 
@c TODO: intention is ``Griff-Übung'' (finger exercise)
Chybnì zadaná písmena jsou indikována obráceným @code{^},
nebo @code{>}, pokud je ¹patnì zadaným znakem konec øádky.
Na konci cvièení program spoèítá skuteènou a u¾iteènou 
rychlost v jednotkách slov za minutu. Pokud jste udìlali pøíli¹ mnoho
chyb, cvièení se spustí znova.

@c TODO: make this less formal
Není dovoleno zpìtnì opravovat ¹patnì zadané znaky.

V rychlostních testech zobrazuje gtypist text na obrazovce a
èeká, a¾ ho u¾ivatel pøepí¹e tím samým. Chyby se zobrazují
a na konci testu se spoèítá opravdová a u¾iteèná rychlost ve
WPM (words per minute -- slova za minutu).
@c TODO: what is it used for ?
Pokud se vyskytlo pøíli¹ mnoho chyb, test se spustí znovu.
Opravování chyb je povoleno, ale takto opravené chyby budou stejnì 
zapoèítány do hodnocení.

Jestli jste ji¾ udìlali pøíli¹ mnoho chyb, mù¾ete pou¾ít @key{ESC} 
a test se spustí znovu. Kdykoliv dokonèíte lekci, butete dotázáni,
zda ji chcete opakovat.

@c TODO: indicate ``practice only'' exercises in modeline ?
GNU Typist obsahuje i cvièení zamìøené pouze na procvièování
(jak drilová cvièení, tak rychlostní testy), která mo¾ná nebudete
muset vùbec opakovat. Nechceme ale øíkat, zda se to týká zrovna
vás, tak¾e se stejnì budete muset sna¾it, jak nejlépe umíte ;-)

@c TODO: restart the drill from the beginning
@c TODO: from the beginning. ??

@c There are two types of drills - one-time and ordinary. In an ordinary
@c drill, gtypist displays text on the screen, and waits for the user to
@c correctly type the exact same text, underneath. It indicates typing
@c errors, and if at the end of the exercise there were errors, it will
@c re-run the drill, up to a maximum number of tries. In a one-time drill,
@c the procedure is the same, except that the program will not repeat the
@c drill if it is not typed correctly. Backspace and delete are not
@c permitted in drills.

@c A speed test is run only once, no matter how many errors
@c there were. Backspace and delete are permitted, but errors still
@c accumulate.

@c @item D
@c This creates an ordinary typing drill. It is a multi-line command;
@c as many lines may be used as available on the screen. 
@c The text is displayed  alternate screen lines, and prompts
@c you to type the same text in on the intermediate lines.  Typing errors
@c are indicated with an inverse @code{^}, or @code{>} if the character is a newline.
@c The drill completes when it is typed correctly, or after a
@c number of attempts.  Delete and backspace are not recognised.  @key{Escape}
@c may be used to exit from the drill before completion.
@c @item O
@c This creates a one-time typing drill. It has the same behaviour as
@c the @code{D} command, but it does not repeat until the text is
@c typed correctly.
@c @item P
@c This creates a speed test. It is a multi-line command; as many lines
@c may be used as are available to curses. It  displays its text on the screen,
@c and prompts you to type on top of it.  Typing errors are highlighted in inverse
@c colours.  You get only one chance at this test, but delete and backspace
@c are recognised (errors still accumulate, however).  At the end
@c of the test, the typing speed and accuracy are displayed.

Ve výsledcích rychlosti znamená jedno slovo pìt znakù, tak¾e
hrubé WPM je poèet znakù v testovací oblasti dìlené pìti a znovu
dìlené poètem uplynulých minut. Co se týèe faktoru chyby, který
WPM ovlivòuje, ka¾dá chyba je poèítaná za ¹patné slovo.

@node Spou¹tìní, Dostupné lekce, Úvod, Top
@chapter Spou¹tìní

Syntaxe pro spu¹tìní GNU Typist je:

@code{gtypist [ parametry... ] [ script_file ]}

Podporované parametry jsou popsány ní¾e (pozor, dlouhé tvary
nejsou v DOSu podporovány).

@table @code

@item -e, --error-max
Udává maximální procento chybovosti pøi zadávání textu.
Defaultní hodnota je 3,0. Musí být mezi 0,0 a 100,0.
Existuje i pøíkaz skriptovacího jazyka
(@pxref{Pøíkazy skriptovacího jazyka}), který to mù¾e zmìnit,
pokud je zadané èíslo men¹í. Pro procvièovací lekce je tato
hodnota ale ignorována.

@item -n, --notimer
Normálnì GNU Typist zobrazuje rychlost ve WPM (slova za minutu) jak 
po drilových cvièeních, tak po rychlostních zkou¹kách. Lekce jsou ale 
zøejmì napsané pro program, který zobrazoval rychlost pouze pøi rychlostních 
testech. Abyste gtypist pøinutili k takovémuto chování odpovídajícímu
lekcím, tedy aby nezobrazoval poèet slov za minutu u drilových testù, 
pou¾ijte tento parametr.

@item -t, --term-cursor
gtypist si vytváøí vlastní obdélníèkový kurzor, aby pomohl
u¾ivateli rozli¹it mezi kurzorem a oznaèením chyb v inverzních
barvách. Tímto parametrem takové chování potlaèíme a donutíme program
pou¾ívat standardní kurzor terminálu.

@item -f, --curs-flash
Hodnota tohoto parametru nastavuje blikání obdélníkového kurzoru
v desetinách sekund. Hodnota 0 znamená, ¾e kurzor nebude blikat.
Standardní hodnota je 10, maximální 512. Toto je ignorováno, pokud 
bylo nastaveno -t nebo --term-cursor.

@item -c, --colo[u]rs
Normálnì pou¾ívá gtypist pouze normální a pøevrácené
monochromatické barvy. Tímto parametrem mù¾ete nastavit
barvu popøedí a pozadí na terminálech, které podporují
barevný výstup. Barvy jsou specifikovány jako dvì èísla
mezi 0 a 7. Kódy barev od 0 do 7 znamenají barvu èernou,
èervenou, zelenou, ¾lutou, modrou, magenta a modrozelenou
a bílou. Defalutní nastavení je 7,0 -- bílá na èerném pozadí.
Toto nastavení je ignorováno pokud terminál nepodporuje barvy.

@item -s, --silent 
Kdykoliv narazí gtypist na chybu, zapípá. Tímto nastavením
mù¾ete zvukový signál potlaèit.

@item -q, --quiet
To samé jako -s, --silent.

@item -w, --wpmode
Tímto donutíte gtypist urèitým zpùsobem napodobovat textový
procesor, kdykoliv spou¹tí nìjaké cvièení. Mezeru na konci øádku
bude brát jako korektní znak a pøejde na dal¹í øádku. Pokud stisknete
na konci øádky ENTER, pøesune vás na následující odstavec.
Vícenádobné mezery stlaèí na jedinou a bude pøeskakovat rozdìlovací
èárky na konci øádek.

@item -l, --start-label
Tento parametr udává návìstí ve skriptovém souboru, kde
gtyping zaène (pro informace o návìstí
viz ní¾e skriptovací jazyk). Pokud není start_label definováno, zaène 
se od zaèátku souboru.

@item -k, --no-skip
Zaká¾e u¾ivateli pøeskakovat lekce nebo z nich utíkat pomocí
@key{ESC ESC}.

@end table

@noindent
Pokud chcete spou¹tìt gtypist ve svém rodném jazyce, musíte
také vhodnì nastavit promìnnou prostøedí @env{LANG} 
@xref{Promìnné prostøedí}.

@strong{Pøíklady:}

@noindent
Ke spu¹tìní standardního anglického souboru lekcí @file{gtypist.typ}:@*
@code{gtypist}


@noindent
Ke spu¹tìní èeských lekcí: @*
@code{gtypist cs.typ}


@noindent
Donutíme gtypist, aby hledal lekci bar.typ v nestandardním 
adresáøi @file{/home/foo}: @*
@code{export GTYPIST_PATH="/home/foo"}
@code{gtypist bar.typ}


@noindent
Abychom mohli spustit lekci @file{test.typ} v adresáøi @file{/tmp},
a zaèít na návìstí @code{TEST1}, v tichém módu, za pou¾ití
standardního kurzoru terminálu, zadáme toto:@*
@code{gtypist -t -q -l TEST1 /tmp/test.typ}

@node Dostupné lekce, Pou¾ívání typefortune, Spou¹tìní, Top
@chapter Dostupné lekce

S GNU Typist jsou dodávány tyto lekce :
@table @file
@item cs.typ
Soubor QWERTY kurzù v èe¹tinì (+ numerická klávesnice)
@item q.typ
Rychlý QWERTY kurz v angliètinì
@item r.typ
Dlouhý QWERTY kurz v angliètinì
@item t.typ
QWERTY výuka v angliètinì
@item v.typ
Je¹tì dal¹í QWERTY v angliètinì
@item w.typ
QWERTY opakování v angliètinì
@item d.typ
Výuka klávesnice Dvorak v angliètinì
@item m.typ
Drilová cvièení v angliètinì
@item s.typ
Rychlostní testy v angliètinì
@item n.typ
Numerická klávesnice v angliètinì
@item gtypist.typ
Soubor v¹ech pøedchozích anglických lekcí
@item esp.typ
Kurz QWERTY ve ¹panìl¹tinì
@item kt*.typ
Toto jsou standardní lekce z Ktouch 1.0
(@url{http://ktouch.sourceforge.net}), které byly
do formátu gtypistu zkonvertovány s pou¾itím
@file{tools/ktouch2typ.pl}.

Tyto soubory jsou ktde.typ (german.ktouch), kten.typ (english.ktouch),
ktfr.typ (french.ktouch), ktlecten.typ (lecture_en.ktouch), ktno.typ
(norwegian.ktouch) and ktnumber.typ (number.ktouch).
@item ttde.typ
To je nìmecká lekce pro tipptrainer
(@url{http://www.pingos.schulnetz.org/tipptrainer}), která byla
zkonvertována s pomocí @file{tools/tt2typ.pl}.
@end table

@noindent
Pokud v tìchto lekcích najdete chyby, pokud nìjakou upravíte,
nebo pokud napí¹ete lekci novou, prosím vydejte ji pod
svobodnou licencí a øeknìte nám o tom -- mù¾ete nám napsat
mail na @email{bug-gtypist@@gnu.org}.

@node Pou¾ívání typefortune, Pøíkazy skriptovacího jazyka, Dostupné lekce, Top
@chapter Pou¾ívání typefortune

`typefortune' vám dovolí cvièit s textem z `fortune'.

@code{SYNTAX: typefortune [-dslh] [-n poèet] [-o <parametry_gtp>]}

@table @code

@item -d
Pou¾ije @code{D:} místo @code{S:}.

@item -s
Spustí fortune s @code{-s}.

@item -l
Spustí fortune s @code{-l}.

@item -n <poèet>
Cvièení <poèet> fortunes.

@item -o <gtypist_options>
Pøedej gtypistu nastavení ve formì @option{option} (nastavení pøepínaèe,
napø. @code{-o word-processor}), @option{option,value} (nastavení hodnoty, 
napø. @code{-o e,1.0}) kde @code{option} je jméno nastavení
(zkrácené èi dlouhé) s tím, ¾e v¹echny úvodní pomlèky jsou odstranìny.
Pokud uvádíte více ne¾ jeden parametr, musíte je uvést v apostrofech:
@command{typefortune -n 3 -o 'silent e,5 word-processor'}.

@end table

@node Pøíkazy skriptovacího jazyka, Vytvoøte nové lekce, Pou¾ívání typefortune, Top
@chapter Pøíkazy skriptovacího jazyka

GNU Typist naèítá data pro jednotlivé lekce ze skriptového
souboru. Ka¾dá øádka s výjimkou komentáøù a prázdných øádek
má následující formát

@code{znak_pøíkazu : data_pøíkazu}

@noindent

@code{Znak pøíkazu} je jeden znak, který urèuje, co bude
gtypist dìlat, a @code{data_pøíkazu} jsou data, se kterými
bude operovat. Pokud je  @code{znak_pøíkazu} mezera, znamená
to, ¾e øádka je pokraèováním pøedchozího pøíkazu.
Oddìlovaè ':' musí být v¾dy v druhém sloupci øádky.

Øádky komentáøù jsou øádky zaèínající znakem '#' a stejnì
jako prázdné øádky jsou ignorovány. Komentáøe mohou mít
jakýkoliv formát, jediným po¾adavkem je, aby zaèínaly '#'.
V¹echny ostatní øádky musí mít vý¹e uvedený formát.

Abyste se seznámili se základy, mìli byste si pøeèíst @xref{Úvod}.

Následující výèet je seznamem platných hodnot @code{znakù_pøíkazu}:

@table @code
@item B
Tento pøíkaz sma¾e celou obrazovku. Pokud má nìjaká 
@code{data_pøíkazu}, ta jsou zobrazena v horním jednoøádkovém
banneru a zùstanou tam a¾ do zavolání následujícího pøíkazu @code{B}. 
Tento pøíkaz nesmí pokraèovat na následující øádce.

@item T
T znamená tutoriál. Pøíkaz mù¾e zpracovávat více øádek
a to a¾ do zaplnìní obrazovky. Ka¾dá øádka pøíkazu je
prostì vyti¹tìna na obrazovku. Pøíkaz sma¾e obrazovku
pod horním jednoøádkovým bannerem. Kdy¾ je zobrazování
hotovo, program èeká na u¾ivatelský vstup. Toho je také
vyu¾íváno pro tisk polo¾ek menu.

@item *
Hvìdièka znamená návìstí v souboru. Návìstí mù¾e být cílem pro
pøíkazy @code{G}, @code{Y}, @code{N} nebo @code{F}. Návìstí
mohou zahrnovat jakékoliv znaky vèetnì mezer a jsou 
jednoøádkovým pøíkazem. Mezery na konci návìstí jsou ignorovány.

@item I
Tento pøíkaz zobrazí struèné instrukce k drilovému èi rychlostnímu
testu. Je dovoleno pou¾ít pouze dvou øádek. Narozdíl od pøíkazu @code{T} 
se pøed pokraèováním neèeká na stisk klávesy. Znaèka by tedy
mìla být v¾dy následována cvièením. Ma¾e plochu obrazovky
pro cvièení, v tomto ohledu se chová jako dvouøádkové @code{T}.

@item M
Tento pøíkaz je nový zpùsob, jak vytváøet menu (od gtypistu 2.7)
Zde je jeho syntax:
@example
M: [UP=(LABEL|_EXIT)] "název"
 :LABEL1 "popis1"
 :LABEL2 "popis2"
 ...
@end example

UP-label oznaèuje návìstí otcovského uzlu, které definuje
poslední polo¾ku menu (pokud je to _EXIT, pak ,,Konec'',
jinak bude poslední polo¾ka v menu ,,Zpìt'' skákat
na zadaný uzel). Tento argument je volitelný. Pokud
není pøítomen, pou¾ije se defaultní _EXIT.

Název, stejnì jako ostatní popis, musí být v uvozovkách ("").
Navíc musí mezi UP=XXX a "název" èi mezi návìstími
a jejich popisem být alespoò jedna mezera.

Pøíklady hledejte v existujících lekcích.

@c TODO: more information about ``should be used for''...
@item D,d
Tento pøíkaz se nazývá ,,drill''  a je jedním ze dvou typù
cvièení.

Je to víceøádkový pøíkaz. Text je zobrazován v ka¾dé druhé
øádce a u¾ivatel jej opisuje do prostoru mezi nimi.
To je dùvod, proè nemù¾ete pou¾ít více jak 11 øádek
obsahu.

Tento typ cvièení by mìl být pou¾íván pouze pro cvièení
prstù (napø. jfjfjjf), ale mù¾e obsahovat i celá slova
a vìty, kdy¾ jsou vyu¾ívány k procvièování (písmeno, slabika)
a nejedná se o opravdové texty.

Verze s malým písmenem @code{d} znamená ,,pouze procvièování'',
u¾ivatel nebude muset cvièení opakovat ani pokud udìlal pøíli¹
mnoho chyb.

@c TODO: more information about ``should be used for''...
@item S,s
To je druhý typ cvièení: ,,rychlostní test''.

Jedná se o víceøádkový pøíkaz. Zobrazuje svùj obsah na obrazovce
a èeká, a¾ jej u¾ivatel pøepí¹e tím samým textem. Proto mù¾ete
na jeden rychlostní test pou¾ít a¾ 22 øádek. V tomto druhu testu
mù¾ete své chyby opravovat, poèítadlo ve statistice je ale stále
bude poèítat jako chyby.

Rychlostní testy by mìly být pou¾ívány pro opisování
kompletních vìt, textù a souborù (napø. dopis, texinfo,
html èi tex soubor).

Verze s malým písmenem @code{s} je rychlostní test
,,pouze k procvièování'', co¾ znamená, ¾e ani u¾ivatel,
který udìlá pøíli¹ mnoho chyb, jej nebude muset opakovat.

@item G
Toto pøinutí gtypist pøeskoèit na návìstí v @code{datech_pøíkazu}
a pokraèovat ve vyvolávání skriptu odtud. Jde o jednoøádkový
pøíkaz.

@item Q
Tento pøíkaz vypí¹e svùj text na stavové øádce a pøed
pokraèováním èeká na klávesu @key{Y} nebo @key{N}.
Ostatní znaky jsou ignorovány.

Jako vedlej¹í efekt mù¾ete také stisknout F-klávesu,
pokud je potøeba (nyní by ji¾ nemìl být tento pøíkaz
pou¾íván pro vytváøení promptu pro menu -- pou¾ijte
radìji pøíkaz M).

@item Y
Y Je podobné @code{G}, s výjimkou toho, ¾e pøíkaz skoku
je vyvolán pouze pokud odpovìï na pøedchozí otázku @code{Q} 
byla @key{Y}.

@item N
N je podobné @code{G}, s výjimkou toho, ¾e pøíkaz skoku
je vyvolán pouze pokud odpovìï na pøedchozí otázku @code{Q} 
byla @key{N}.

@item K
@emph{Tento pøíkaz by ji¾ nemìl být pou¾íván, pou¾ijte M}
Vá¾e funkèní klávesu na návìstí. Formát dat následujících
tento pøíkaz musí být @code{Fklávesa:návìstí}, kde
@code{Fklávesa} je èíslo funkèní klávesy mezi 1 a 12
a @code{návìstí} je místo, kam se pøesunout po stisku
této klávesy. Hodnota návìstí NULL klávesu znefunkèní.

Pokud na terminálu nejsou dostupné funkèní klávesy,
mohou být místo jich pou¾ity klávesy
@key{1} a¾ @key{9} pro @key{F1} a¾ @key{F9}, @key{0} pro
@key{F10}, @key{A} pro @key{F11} a @key{S} pro @key{F12}.

Jinou alternativou pro @key{F1} a¾ @key{F12} jsou kombinace: 
@key{Ctrl-Q}, @key{Ctrl-W}, @key{Ctrl-E}, @key{Ctrl-R}, 
@key{Ctrl-T}, @key{Ctrl-Z}, @key{Ctrl-U}, @key{Ctrl-I}, 
@key{Ctrl-O}, @key{Ctrl-P}, @key{Ctrl-A} a @key{Ctrl-S}.

To je také u¾iteèné, pokud jsou funkèní klávesy odchytávány
jinými programy (napøíklad window managery).

@item E
Tento pøíkaz je pou¾íván pro nastavení nejvy¹¹ího procenta
chyb dovoleného pro úspì¹né absolvování následující lekce
(E:<value>%) èi pro v¹echny lekce a¾ do dal¹ího výskytu E
(E:<value>%*).

Pokud je nastaveno @option{--error-max/-e}, tak bute tento
pøíkaz platit pouze tehdy, pokud je @emph{pøísnìj¹í} 
ne¾ hodnota specifikovaná na pøíkazové øádce.

@code{data_pøíkazu} se skládají z hodnoty (mezi 0.0 a 100.0)
následované znakem '%' (toto je po¾adováno, aby byly skripty
lépe èitelné). Existuje speciální hodnota @code{default} 
nebo @code{Default}, která nastavuje maximální procento chyb
zpìt na defaultní hodnotu.

@item F
Tento pøíkaz mù¾e být pou¾it k nastavení návìstí 
(v @code{data_pøíkazu}), kam bude u¾ivatel muset 
jít, pokud úspì¹nì neprojde cvièením.

Tento pøíkaz se vìt¹inou vztahuje pouze k následujícímu
cvièení, ale pokud na konec @code{dat_pøíkazu}
vlo¾íte '*', mù¾ete jej tak uèinit trvale platným.

Pokud je návìstí NULL, pak pøíkaz návìstí resetuje.

@item X
Tento pøíkaz pøinutí gtypist vyskoèit. Je to jednoøádkový
pøíkaz. Jakékoliv @code{data_pøíkazu} jsou ignorována. 
Jiný zpùsob, jakým mù¾e dojít k opu¹tìní programu,
je kdy¾ gtypist dojde na konec souboru (tak¾e tam mù¾ete
také umístit návìstí a odkazovat na nìj pøíkazem @code{G})

@end table

@c TODO: more examples (i.e. one example for E:/F:, one for a menu, ...)

Prohlédnìte si malý pøíklad skriptu, který demonstruje
dostupné pøíkazy (soubor lekce @file{tinydemo.typ}):

@example
# Malý pøíklad
B: Demonstrace tutoriálu
*:LOOP
K:1:QDONE
T:Zde je malý pøíklad skriptu pro lekci.
 :Lep¹í pøíklad mù¾ete nalézt v souboru
 :demo.typ, který je dodáván s GNU Typist.
I:Tady je drilové cvièení: 
D:asdf ghjkl;
I:A tady je zas rychlostní test: 
S:qwe rt yu iop
*:QDONE
Q:Staèilo to ji¾? [Y/N] 
N:LOOP 
X:
@end example

@node Vytvoøte nové lekce, Mód Emacsu, Pøíkazy skriptovacího jazyka, Top
@chapter Vytvoøte nové lekce

This section provides guidelines and hints for creating new lessons
(or improving existing ones).

@c TODO: better name for ``Design patterns'' ??

@menu
* Ktouch lessons::              Generate lessons from a set of drills
* Exercises from fortune::      Create drills/speedtests with text from fortune
* Design patterns for lessons:: Hints/Design patterns for lessons
@end menu

@node Ktouch lessons, , Exercises from fortune, Vytvoøte nové lekce
@section Ktouch lessons

A very easy way to write lessons is to write them in the format
that @command{ktouch} uses, and then convert it to a gtypist lesson
using @command{tools/ktouch2typ.pl}. This will take care of writing
``jump-tables'', a menu and a bit more.

The ktouch-format consists only of lessons, which are preceded by
their names, and separated by blank lines and/or comments (# at the
beginning of the line). So the first non-blank, non-comment line in
the file is the name of the first lesson, and the first lesson
consists of all the lines up to the next comment or blank line. After
the separator (comment or blank line) the name of the second lesson
follows and so on.

This is an example of a three-lesson ktouch file (excerpts from the
first three lessons of german.ktouch):
@example
#
# Deutsche Training-Datei für KTouch
#

Grundstellung
f f f f f f fff fff fff f f f f f f fff fff fff f f f f f f f fff
j j j j j j jjj jjj jjj j j j j j j jjj jjj jjj j j j j j j j jjj
fff jjj fff jjj jjj fff jjj fff fjf fjf fjf jfj jfj jfj fjf jfjfj

Grundstellung
fff jjj ddd kkk aaa ööö fff jjj ddd kkk aaa ööö fff jjj ddd kkkff
fda jkö fda jkö fda jkö fda jkö fda jkö fda jkö fda jkö fda jköfd
s s s s s s sss sss sss s s s s s s sss sss sss s s s s s s s sss

#Zwei wichtige Vokale: e und i
e und i
asdf ölkj fdsa jklö asdf ölkj fdsa jklö asdf ölkj fdsa jklö asdfö
das dass lös fad dass lös als dass las lös fad dass als dass dass
ded ded ded dej dek del deö ded deö del dek dej ded dej dek delde
@end example

Once you are done, use @command{tools/ktouch2typ.pl} to convert the
file: @samp{ktouch2typ.pl lesson.ktouch} converts @file{lesson.ktouch}
to @file{lesson.typ}. It is important that the input file ends in
``.ktouch'', otherwise @command{ktouch2typ.pl} will skip it. Warning:
this will overwrite @file{lesson.typ} without asking you !

You can customize the number of lines that @command{ktouch2typ.pl}
uses for each drill by modifying the relevant variable in
@file{tools/ktouch2typ.pl}.

Obviously, the disadvantage of this is that you cannot make use of all
of gtypist's features (but the output file is very readable, so you
can edit it to use more of gtypist's features).

@node Exercises from fortune, Ktouch lessons, Design patterns for lessons, Vytvoøte nové lekce
@section Exercises from fortune

Using @file{gtypist-mode.el} you can quickly create lessons with text
from the program @command{fortune} (or the emacs-internal
@command{yow} if @command{fortune} isn't available, as is usually the
case on Windows).

Once you installed @file{gtypist-mode.el} 
(@pxref{Mód Emacsu}), you can open a file
with it ``.typ'' extension and run @kbd{C-c C-f} to create a drill
(@code{D:} by default, use @kbd{C-u} or @kbd{C-u C-u} prefix to
change).

@node Design patterns for lessons, Exercises from fortune, , Vytvoøte nové lekce
@section Design patterns for lessons

@subsection Structure of lesson files

@itemize @bullet
@item use mixture of drills and speed tests (this is more fun for the user)
@item use some ``practice-only'' exercises (d:/s:) (possibly mixed with
``real'' exercises) followed by a ``final test''.
@file{esp.typ} uses this scheme.

@end itemize

@subsection Patterns for exercises

@itemize @bullet
@item when introducing a new key, start out by mixing other (known) keys
of the same finger in with the new key in the first drill(s).
Here is an example (from @file{t.typ}, line 237):
@example
I:Use your J-finger for the H key.
*:_T_R_L23
D:jjj jhj jjj jhj jjj jhj
@end example
@item use 'word, word.' repeatedly to practice ,/.
@end itemize


@node Mód Emacsu, Promìnné prostøedí, Vytvoøte nové lekce, Top
@chapter Mód Emacsu

gtypist now comes with an Emacs major-mode which does
syntax-highlighting, indentation and has some convenient commands for
counting labels, a goto-label-command, inserting properly centered
banners, special comments and a bit more.

Copy this file from @file{tools/gtypist-mode.el} to wherever you put 
your local elisp files (e.g.  @file{~/elisp}) and put this in your 
@file{~/.emacs} (adapt path!):

@lisp
(autoload 'gtypist-mode "~/elisp/gtypist-mode")
@end lisp

or put it in @code{load-path} (@samp{make install} in the
sources should take care of this for GNU Emacs, or if you
are using the Debian package, it installs it here for you)
and use this instead:

@lisp
(autoload 'gtypist-mode "gtypist-mode")
@end lisp

@strong{and} add this to your @file{~/.emacs}:

@lisp
(setq auto-mode-alist       
      (cons '("\\.typ\\'" . gtypist-mode) auto-mode-alist))
@end lisp

@c If you want to, you can then byte-compile the file using
@c @kbd{M-x byte-compile-file} (but @samp{make install} takes care of
@c this).

@noindent
All this is also mentioned in the README-section of
@file{tools/gtypist-mode.el}.

@noindent
Here are the commands along with the keybindings:

@table @kbd

@item C-c C-i, M-x gtypist-mode-info
This shows gtypist's texinfo-documentation, starting at node
``Script file commands'' (@pxref{Pøíkazy skriptovacího jazyka}). With prefix,
start at the top-node.

@item C-c M-g, M-x gtypist-mode-goto-label
Query for a label to go to (with completion).

@item C-c C-l, M-x gtypist-mode-next-label
This command inserts the next label in a numbered sequence of labels.
For example, if you insert
@example
*:SERIES1_L1
@end example
and hit @kbd{C-c C-l} then gtypist-mode will insert
@example
*:SERIES1_L2
@end example

@item C-c C-b, M-x gtypist-mode-insert-banner
This command inserts a centered @code{B:} command. It's centered on
66 columns because ``gtypist <version>'' is in the right corner
(prompts for content).

@item C-c C-r, M-x gtypist-mode-insert-hrule
Inserts a horizontal rule (comment) consisting of dashes.

@item C-c C-n, M-x gtypist-mode-new-lesson
Insert the comments (header) and a label to start a new lesson
(prompts for name).

@item C-c C-f, M-x gtypist-mode-fortune-to-drill
Insert a drill (@code{D:}) with text from @command{fortune} (or
@command{yow} if @command{fortune} isn't available). Use @kbd{C-u}
prefix to get @code{S:}, and @kbd{C-u C-u} to get @code{d:}.

@end table

@noindent
Run @kbd{C-h m} for a complete list of commands and their keybindings.

If you find bugs or if you think there's something else this mode could
do, please write to @email{bug-gtypist@@gnu.org}.

@node Promìnné prostøedí, Chyby a opominutí, Mód Emacsu, Top
@section Promìnné prostøedí
GNU Typist pou¾ívá tyto promìnné prostøedí:

@table @code

@item LANG

GNU Typist nabízí Native Language Support (NLS) s podporou
knihovny gettext. To znamená, ¾e pokud to vá¹ systém podoruje,
mù¾ete si vybrat jazyk, ve kterém chcete zobrazovat hlá¹ky gtypistu.
Momentálnì jsou k dispozici angliètina, ¹panìl¹tina, nìmèina,
fin¹tina a èe¹tina. K pou¾ití konkrétní NLS je tøeba nastavit
promìnnou prostøedí LANG na odpovídající LL_CC kombinaci, 
kde LL je dvouznakový kód jazyka podle ISO 639 a CC je dvoupísmenný
znak zemì podle ISO 3166 (napø. es_ES pro ©panìlsko nebo de_DE
pro Nìmecko). Na nìkterých systémech budete muset asi nastavit
na tu samou hodnotu i promìnnou LANGUAGE.

Pokud chcete pøelo¾it zprávy do nìjakého jiného jazyka, nebo pokud
chcete nìco opravit, ozvìte se prosím na
@email{bug-gtypist@@gnu.org}.


@item GTYPIST_PATH
Seznam adresáøù, kde bude program hledovat skriptovací soubory.
Dodr¾uje standardní zpùsob specifikace adresáøù, to znamená
seznam adresáøù oddìlených znaky ':'. GNU Typist se pøi spu¹tìní
nejprve pokusí skript spustit z aktuálního adresáøe a poté
bude hledat v adresáøích specifikovaných promìnnou @code{GTYPIST_PATH}.
Nakonec se podívá do adresáøe vytvoøeného pøi instalaci.
(Napø. @file{/usr/local/share/gtypist} nebo @file{/usr/share/gtypist}).

@item TERM
Tuto promìnnou pou¾ívá knihovna curses k urèení obrazovky.

@item TERMINFO
Tento parametr budete muset zmìnit, pokud jsou adresáøe s
 @code{terminfo} rozdílné na systému, kde byl gtypist kompilován
a na systému, kde má fungovat. Napøíklad na star¹ích
distribucích Slackware je terminfo umístìno v
@file{/usr/lib/terminfo}. Na RedHat Linuxu je v 
@file{/usr/share/terminfo}. Pokud si program stì¾uje
na typ terminálu a má správnì nastavenou hodnotu
@code{TERM}, zkuste toto.

@end table

@node Chyby a opominutí, Historie, Promìnné prostøedí, Top
@section Chyby a opominutí

GNU Typist se nijak nesna¾í minimalizovat výstup na terminál.
Speciálnì blikající kurzor mù¾e pùsobit hodnì pohybu. Pokud
by to byl problém, pou¾ijte kurzor terminálu.

V rychlostních testech není mo¾né pou¾ívat backspace a delete
za zaèátkem nové øádky nebo po klávese TAB. To je kvùli zjednodu¹ení
aktualizace obrazovky.

Barevné módy zøejmì nepracují dobøe s UnixWare. Nìkdy 
nejsou správnì zobrazeny pøevrácené barvy. To se týká nìkterých
typù terminálù a xterminálù.

@node Historie, Kopírování tohoto manuálu, Chyby a opominutí, Top
@appendix Historie GNU Typist

@itemize @bullet
@item
Pùvodní program byl napsán pro VAX/VMS BASIC nìkým z Harris
Corp (Ft. Lauderdale, FL).
@item
D. Jason Penney @email{penneyj@@slc.com} jej pøepsal pro Microsoft BASICA
@item
D. Jason Penney @email{penneyj@@slc.com} jej pøepsal pro C s knihovnou curses
@item
Simon Baldwin @email{simonb@@sco.com} pøepsal verzi D. Jason Penneyho,
jeho vylep¹ení jsou popsána v souboru NEWS (mezi verzí 2.2 a 2.2b).
On je také dr¾itelem copyrightu na GNU Typist
(gtypist je distribuovaný pod podmínkami GNU GPL).
Simon také napsal verzi Typistu v Javì, kterou pùvodnì nazýval 
JTypist, ale nyní se jmenuje Typist:
@url{http://www.geocities.com/simon_baldwin/typist/}
@item
Since 1997, Ben Armstrong @email{synrg@@sanctuary.nslug.ns.ca} 
pomohl opravováním chyb a udr¾ování balíèku pro Debian
(podívejte se na
@url{http://packages.debian.org/gtypist}).
@item
V roce 2000 se Vladimir Támara @email{vtamara@@users.sourceforge.net} a
Igor Támara @email{ikks@@users.sourceforge.net} stali maintainery verze 
v C. Pøed listopadem 2000 byl GNU Typist spravován jako souèást
projektu Structio.
@item
Listopad 2000, program byl pøijat do GNU! Byl pøejmenován na GNU Typist
(také gtypist).
@item V kvìtnu 2001 se stal novým maintainerem 
Michael Opdenacker @email{michaelo@@gnu.org},
který se také nauèil psát na klávesnici s gtypistem.
Vývoj projektu nyní probíhá na
@url{http://savannah.gnu.org/projects/gtypist/}.
@item V èervnu 2001 se k projektu pøipojil 
Felix Natter @email{f.natter@@ndh.net} 
a výraznì mu pøispìl portováním
lekcí z jiných tutoriálù, vylep¹ením pomocných utilit,
nových mo¾ností tutoriálù a módem pro Emacs.
@end itemize

@node Kopírování tohoto manuálu
@appendix Kopírování tohoto manuálu
@menu
* GNU Free Documentation License:: Kopírování tohoto manuálu
@end menu

@include fdl.texi
@bye

@c  LocalWords:  xref QWERTY kt
