/* Automatically generated by po2tbl.sed from gtypist.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"line", 2},
  {"data shortage", 3},
  {"missing ':'", 4},
  {"line too long for screen", 5},
  {"internal error: malloc", 6},
  {"label redefinition", 7},
  {"label '%s' not found", 8},
  {"internal error: fseek", 9},
  {"invalid key binding (%d:%s)", 10},
  {"invalid function key number", 11},
  {"data exceeds screen length", 12},
  {"instructions are limited to two lines", 13},
  {"unknown command", 14},
  {"\
run drills N times on errors (default 3), valid   values are between 1 and \
1000", 15},
  {"turn off WPM timer in drills", 16},
  {"use the terminal's hardware cursor", 17},
  {"\
cursor flash period P*.1 sec (default 10), valid  values are between 0 and \
512, ignored if -t", 18},
  {"set initial display colours where available", 19},
  {"don't beep on errors", 20},
  {"same as -s, --silent", 21},
  {"start the lesson at label 'L'", 22},
  {"try to mimic word processors", 23},
  {"print this message", 24},
  {"output version information and exit", 25},
  {"\
`gtypist' is a typing tutor, with several lessons for different keyboards \
and    languages.  New lessons can be written by the user easily.\n\
\n", 26},
  {"Usage", 27},
  {"Options", 28},
  {"script_file", 29},
  {"\
\n\
If not supplied, script_file defaults to '%s/%s'.\n", 30},
  {"\
The path $GTYPIST_PATH is searched for script files.\n\
\n", 31},
  {"Examples", 32},
  {"To run the default lesson in english `gtypist.typ'", 33},
  {"To run the lesson in spanish", 34},
  {"\
To instruct gtypist to look for lesson `bar.typ' in a non standard directory", 35},
  {"\
To run the lesson in the file `test.typ' of directory `temp', starting at \
label `TEST1', using the terminal's cursor, and run silently", 36},
  {"Report bugs to bug-gtypist@gnu.org", 37},
  {"%s: invalid drill-tries value\n", 38},
  {"%s: invalid curs-flash value\n", 39},
  {"%s: invalid colours value\n", 40},
  {"%s: internal error: malloc\n", 41},
  {"Written by Simon Baldwin", 42},
  {"Try '%s --help' for more information.\n", 43},
  {"\
Copyright (C) 1998,2000  Simon Baldwin.\n\
This program comes with ABSOLUTELY NO WARRANTY; for details\n\
please see the file 'COPYING' supplied with the source code.\n\
This is free software, and you are welcome to redistribute it\n\
under certain conditions; again, see 'COPYING' for details.\n\
This program is released under the GNU General Public License.", 44},
  {" Tutorial ", 45},
  {"  Query   ", 46},
  {"  Drill   ", 47},
  {"Speed test", 48},
  {" Press Return to continue... ", 49},
  {" Please try again, %d of %d; press Return to continue... ", 50},
  {" Raw speed      = %6.2f wpm ", 51},
  {" Adjusted speed = %6.2f wpm ", 52},
  {"            with %3.0f%% errors ", 53},
  {"can't find or open file", 54},
};

int _msg_tbl_length = 54;
